FROM tomcat:8-jdk11-openjdk

ARG TOMCAT_DIR=/usr/local/tomcat
ARG USERNAME=activiti
ARG USERID=33007
ARG CONTENT_STORAGE_DIR=/data


USER root

RUN useradd -c "Activiti" -M -s "/bin/bash" -u "${USERID}" -o "${USERNAME}"

RUN rm -rf $TOMCAT_DIR/webapps/activiti-rest

COPY --chown=${USERNAME} wars/activiti-rest.war $TOMCAT_DIR/webapps

RUN unzip $TOMCAT_DIR/webapps/activiti-rest.war -d $TOMCAT_DIR/webapps/activiti-rest
RUN rm $TOMCAT_DIR/webapps/activiti-rest.war

COPY --chown=${USERNAME} config/rest/activiti-rest.properties $TOMCAT_DIR/webapps/activiti-rest/WEB-INF/classes/db.properties
COPY --chown=${USERNAME} config/rest/engine.properties $TOMCAT_DIR/webapps/activiti-rest/WEB-INF/classes/engine.properties

COPY --chown=${USERNAME} logging/activiti-rest-log4j.properties $TOMCAT_DIR/webapps/activiti-rest/WEB-INF/classes/log4j.properties

COPY --chown=${USERNAME} config/setenv.sh ${TOMCAT_DIR}/bin

RUN chown ${USERNAME}:${USERNAME} -R /usr/local/tomcat

RUN mkdir -p ${CONTENT_STORAGE_DIR}
RUN chown ${USERNAME}:${USERNAME} ${CONTENT_STORAGE_DIR}

USER ${USERNAME}